# torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 8 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 4 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 4 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 2 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 2 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 1 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 1 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 8 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage
# torchrun --nproc_per_node 4 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 4 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage
# torchrun --nproc_per_node 2 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 2 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage
# torchrun --nproc_per_node 1 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 1 --num-epochs 7 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage

torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 8 --num-epochs 40 --fan-out 12,12,12 --num-hidden 256 --breakdown --model sage --eval-every 1
torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-papers100M --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-papers100M --num-trainers 8 --num-epochs 40 --fan-out 12,12,12 --num-hidden 256 --breakdown --model gat --num-heads 8 --eval-every 1