# torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 4 --fan-out 20,20,20 --batch-size 1535 --num-hidden 128 --breakdown --eval-every 999 --model sage
# torchrun --nproc_per_node 4 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 4 --num-epochs 4 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 999 --model sage
# torchrun --nproc_per_node 2 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 2 --num-epochs 4 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 999 --model sage
# torchrun --nproc_per_node 1 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 1 --num-epochs 4 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 999 --model sage
torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 4 --fan-out 20,20,20 --batch-size 1535 --num-hidden 128 --breakdown --eval-every 999 --model gat --num-heads 8
torchrun --nproc_per_node 4 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 4 --num-epochs 4 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 999 --model gat --num-heads 8
torchrun --nproc_per_node 2 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 2 --num-epochs 4 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 999 --model gat --num-heads 8
torchrun --nproc_per_node 1 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 1 --num-epochs 4 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 999 --model gat --num-heads 8

# torchrun --nproc_per_node 2 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 2 --num-epochs 80 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 1 --model sage
# torchrun --nproc_per_node 2 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/dgl_workspace/dataset/ogbn-products --num-trainers 2 --num-epochs 120 --fan-out 20,20,20 --batch-size 1536 --num-hidden 128 --breakdown --eval-every 1 --model gat --num-heads 8

