# torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 4 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 4 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 2 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 2 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 1 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 1 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model gat --num-heads 4
# torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage
# torchrun --nproc_per_node 4 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 4 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage
# torchrun --nproc_per_node 2 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 2 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage
# torchrun --nproc_per_node 1 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 1 --num-epochs 10 --fan-out 12,12,12 --num-hidden 32 --breakdown --eval-every 21 --model sage

# torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 12,12,12 --num-hidden 128 --breakdown --model sage --eval-every 1
# torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 12,12,12 --num-hidden 128 --breakdown --model gat --num-heads 8 --eval-every 1

torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 25,25,25 --num-hidden 128 --breakdown --model sage
torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 20,20,20 --num-hidden 128 --breakdown --model sage
torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 15,15,15 --num-hidden 128 --breakdown --model sage
torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 25,25,25 --num-hidden 128 --breakdown --model gat --num-heads 8
torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 20,20,20 --num-hidden 128 --breakdown --model gat --num-heads 8
torchrun --nproc_per_node 8 training/train_node_classification.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 40 --fan-out 15,15,15 --num-hidden 128 --breakdown --model gat --num-heads 8

torchrun --nproc_per_node 8 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 20 --fan-out 25,25,25 --num-hidden 128 --breakdown --model sage --eval-every 21
torchrun --nproc_per_node 8 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 20 --fan-out 20,20,20 --num-hidden 128 --breakdown --model sage --eval-every 21
torchrun --nproc_per_node 8 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 20 --fan-out 15,15,15 --num-hidden 128 --breakdown --model sage --eval-every 21
torchrun --nproc_per_node 8 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 20 --fan-out 25,25,25 --num-hidden 128 --breakdown --model gat --num-heads 8 --eval-every 21
torchrun --nproc_per_node 8 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 20 --fan-out 20,20,20 --num-hidden 128 --breakdown --model gat --num-heads 8 --eval-every 21
torchrun --nproc_per_node 8 training/train_node_classification_gpu.py --dataset ogbn-products --root /home/ubuntu/f2cgt_workspace/dataset/ogbn-products --num-trainers 8 --num-epochs 20 --fan-out 15,15,15 --num-hidden 128 --breakdown --model gat --num-heads 8 --eval-every 21